### ISSUE TITLE
Elements with ::before selector are not affected

### ISSUE THREAD

**Issue by wesamco** [alexanderby/darkreader#129]
here's a example [Flexport website](flexport.com), check it out before they push new code.
the titles' font color in the header are still in their black font color in dark mode.

``` html
<div class="overlay overlayFull zIndexBackground backgroundHero sticky" style="height: 485px;">
    <div class="overlay overlayFull backgroundImageOverlay" style="background-image: url(&quot;//www.flexport.com/assets/pages/heroes/whyflexport-ff8d448f03d6b46f3b263789555721bec617e50c313356d09ba0497688124ac6.jpg&quot;); background-size: cover; background-position: 50% 50%; opacity: 0.2;"></div>
</div>
```

```css
element.style {
    height: 485px;
}
manifest-6985ca…6512780.css:23
.sticky {
    position: fixed !important;
}
manifest-6985ca…06512780.css:5
.overlayFull {
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
}
manifest-6985ca…06512780.css:5
.overlay, .overlayHighlight, .overlayLowlight, .overlayAction, .overlayDefault, .overlayMidnight, .overlayCrimson, .overlayBright, .overlayLight, .overlayTeal, .overlayRed, .overlayBlue {
    opacity: 1;
    z-index: 5;
}
manifest-6985ca…06512780.css:5
.staticOverlay, .overlay, .overlayHighlight, .overlayLowlight, .overlayAction, .overlayDefault, .overlayMidnight, .overlayCrimson, .overlayBright, .overlayLight, .overlayTeal, .overlayRed, .overlayBlue {
    position: absolute;
}
manifest-6985ca…06512780.css:5
.backgroundHero {
    background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiP…dpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JhZCkiIC8+PC9zdmc+IA==);
    background: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #107898), color-stop(100%, #1baada));
    background: -moz-linear-gradient(top, #107898, #1baada);
    background: -webkit-linear-gradient(top, #107898, #1baada);
    background: linear-gradient(to bottom, #107898, #1baada);
}
manifest-6985ca…06512780.css:5
.zIndexBackground, .zIndex-50Background {
    z-index: -50 !important;
}
manifest-6985ca…06512780.css:1
body *, *::before, *::after {
    box-sizing: inherit;
}
manifest-6985ca…06512780.css:5
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
user agent stylesheet
div {
    display: block;
}
Inherited from div
Style Attribute {
    height: 410px;
    padding: 20px 15px;
    display: table-cell;
    vertical-align: middle;
    text-align: center;
    color: rgb(255, 255, 255);
    position: relative;
}
Inherited from div.mNavBody
manifest-6985ca…6512780.css:23
.mNavBody {
    overflow-x: hidden;
    width: 100%;
    -webkit-user-drag: none;
    -webkit-tap-highlight-color: transparent;
}
Inherited from body.vsc-initialized
manifest-6985ca…6512780.css:23
body {
    font-family: "Source Sans Pro", "Helvetica Neue", Helvetica, sans-serif;
    font-size: 16px;
    text-rendering: optimizeSpeed;
    -webkit-font-smoothing: auto;
    -moz-osx-font-smoothing: grayscale;
    -moz-font-feature-settings: "liga" on;
}
manifest-6985ca…06512780.css:5
body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    color: #333;
    background-color: #fff;
}
Inherited from html
<style>…</style>
html {
    text-shadow: 0 0 0 !important;
}
manifest-6985ca…06512780.css:5
html {
    font-size: 62.5%;
    -webkit-tap-highlight-color: transparent;
}
manifest-6985ca…06512780.css:5
html {
    font-family: sans-serif;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
}
Pseudo ::before element
manifest-6985ca…06512780.css:5
*:before, *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
manifest-6985ca…06512780.css:1
body *, *::before, *::after {
    box-sizing: inherit;
}
injected stylesheet
::after, ::before {
    box-sizing: border-box;
}
Pseudo ::after element
manifest-6985ca…06512780.css:5
*:before, *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
manifest-6985ca…06512780.css:1
body *, *::before, *::after {
    box-sizing: inherit;
}
injected stylesheet
::after, ::before {
    box-sizing: border-box;
}
```
