### ISSUE TITLE
On current Dev and Canary builds (Chrome 45), the background is not inverted

### ISSUE THREAD

**Issue by abstiles** [alexanderby/darkreader#6]
I wanted to pass along that this extension is also affected by [Chromium issue 501582](https://code.google.com/p/chromium/issues/detail?id=501582), which prevents CSS filters applied to the root element from affecting the page background.

This is a demonstration of the issue with today's Canary build 45.0.2435.0:
![screen shot 2015-06-18 at 8 32 15 am](https://cloud.githubusercontent.com/assets/1497157/8232409/1431033a-1595-11e5-8a4a-bd3f693bdc85.png)

I hope they acknowledge this as incorrect behavior and fix it before this change flows into the Beta or Stable channels, but it might be prudent to look into workarounds like overriding the background.

**Comment by alexanderby** [comment]
Thanks.
Now it looks like in FireFox. There I used to insert the following rule:
```css
html {
    background-color: black !important;
    filter: invert(100%) hue-rotate(180deg) !important;
    min-height: 100% !important;
}
...
```
Not sure if this will work for background images defined at <html>.
